# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('firstRow', models.CharField(blank=True, max_length=12)),
                ('secondRow', models.CharField(blank=True, max_length=12)),
                ('nuturition_cal', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_protein', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_fat', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_car', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_tsg', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_sodium', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_cole', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_sfa', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_tfa', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_tdf', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_mufa', models.FloatField(blank=True, default=0, null=True)),
                ('nuturition_fapu', models.FloatField(blank=True, default=0, null=True)),
                ('long_description', models.TextField(blank=True, default=0, max_length=300, null=True)),
                ('short_description', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('short_description2', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('percent_cal', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('percent_sugar', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('percent_fat', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('percent_sodium', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('percent_df', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('percent_uf', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('picture_index', models.IntegerField(blank=True, null=True)),
                ('nuturition_glu', models.IntegerField(blank=True, default=0, null=True)),
                ('nuturition_uf', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('produced', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('limit', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('days', models.CharField(blank=True, choices=[('0', '월'), ('1', '화'), ('2', '수'), ('3', '목'), ('4', '금'), ('5', '토'), ('6', '일')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_web', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, null=True)),
                ('prcie', models.IntegerField(default=0, null=True)),
                ('side', models.ManyToManyField(blank=True, null=True, to='product.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Program_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Option')),
                ('its_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('isCustomer', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Program'),
        ),
        migrations.AddField(
            model_name='option',
            name='itself',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Program'),
        ),
    ]
