# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='prcie',
            new_name='price',
        ),
    ]
