# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160720_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='side',
        ),
        migrations.AddField(
            model_name='program',
            name='side',
            field=models.BooleanField(default=False),
        ),
    ]
