# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160722_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='2주', max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Program_duration'),
        ),
    ]
