# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160725_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produced',
            new_name='toBproduced',
        ),
    ]
