# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160726_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='isCustomer',
        ),
        migrations.AddField(
            model_name='schedule',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
