# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160720_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='indicator',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
