# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='isRegistered',
            field=models.CharField(choices=[('0', '비회원'), ('1', '회원'), ('2', 'NAVER'), ('3', 'KAKAO')], default='0', max_length=1, null=True),
        ),
    ]
