# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20160721_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_calendar',
            name='modified',
            field=models.ManyToManyField(blank=True, to='date.Not_availble_date'),
        ),
        migrations.AlterField(
            model_name='member_calendar',
            name='original',
            field=models.ManyToManyField(blank=True, to='date.Availble_date'),
        ),
        migrations.AlterField(
            model_name='member_cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='member_cart',
            name='program',
            field=models.ManyToManyField(blank=True, to='product.Program'),
        ),
    ]
