# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off', models.CharField(blank=True, choices=[('1주년', '1000'), ('2주년', '20000')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime(2016, 7, 14, 18, 8, 43, 188755))),
                ('comment', models.TextField(blank=True, max_length=128, null=True)),
                ('module_info', models.IntegerField(default=0, null=True)),
                ('delivered', models.IntegerField(default=0, null=True)),
                ('toBdelivered', models.IntegerField(default=0, null=True)),
                ('isCustomer', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True, default=datetime.datetime(2016, 7, 14, 18, 8, 43, 188852), null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Order_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('카드', '카드'), ('현금', '현금')], max_length=10, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '주문접수'), ('1', '배송준비'), ('12', '단품 배송준비'), ('13', '단품 배송중'), ('14', '단품 배송완료'), ('22', '프로그램 배송준비'), ('23', '프로그램 배송중'), ('24', '프로그램 배송준비'), ('32', '박스 배송대기'), ('33', '박스 배송준비'), ('34', '박스 배송중'), ('35', '박스 배송완료')], max_length=1, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(default=0, null=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Discount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('1', 'A'), ('2', 'B')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1주', 7), ('2주', 14)], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(choices=[('우체국', '3100'), ('새벽배송', '1234')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_where', models.CharField(choices=[('0', '기본 배송지'), ('1', '주문자 정보와 동일'), ('2', '최근 배송지'), ('3', '새로운 배송\t')], max_length=1, null=True)),
                ('whom', models.CharField(blank=True, max_length=99, null=True)),
                ('delivery_address', models.CharField(max_length=128, null=True)),
                ('cell', models.CharField(blank=True, max_length=11, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('how', models.CharField(blank=True, choices=[('0', '새벽배송(수도권 일부지역만 가능)'), ('1', '우체국배송')], max_length=1, null=True)),
                ('door', models.CharField(blank=True, choices=[('0', '비밀번호'), ('1', '주문자 전화'), ('2', '수령자 전화'), ('3', '경비실 배송'), ('4', '경비실 호출'), ('5', '자유출입')], max_length=1, null=True)),
                ('door_pw', models.CharField(blank=True, max_length=20, null=True)),
                ('door_pw_save', models.BooleanField(default=True)),
                ('requests', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_company')),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_duration')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_iterate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(choices=[('1번', 1), ('2번', 2)], max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='iteration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_iterate'),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='price',
            name='shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_fee'),
        ),
    ]
