# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 14, 18, 8, 45, 708895)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 14, 18, 8, 45, 709029), null=True),
        ),
    ]
