# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20160719_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 13, 33, 38, 113702), null=True),
        ),
    ]
