# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20160719_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 15, 8, 34, 667201), null=True),
        ),
    ]
