# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20160719_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_info',
            name='numOfppl',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 16, 29, 24, 167836), null=True),
        ),
    ]
