# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20160719_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 16, 44, 56, 358623), null=True),
        ),
        migrations.AlterField(
            model_name='shipping_fee',
            name='fee',
            field=models.CharField(choices=[('우체국', 3100), ('새벽배송', 1234)], max_length=10, null=True),
        ),
    ]
