# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20160719_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 16, 52, 26, 751695), null=True),
        ),
        migrations.AlterField(
            model_name='shipping_fee',
            name='fee',
            field=models.CharField(choices=[(3100, '우체국'), (5000, '새벽배송')], max_length=10, null=True),
        ),
    ]
