# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20160719_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 18, 5, 12, 989023), null=True),
        ),
    ]
