# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20160719_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isCustomer',
            new_name='isMember',
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 18, 6, 42, 257706), null=True),
        ),
    ]
