# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_auto_20160720_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 11, 14, 35, 982276), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='thisid',
            field=models.IntegerField(default='4LHM1IGKJDSJIUDH', null=True),
        ),
    ]
