# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20160720_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 11, 19, 32, 749534), null=True),
        ),
    ]
