# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_auto_20160720_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='thisid',
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.IntegerField(default=1290919, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 11, 25, 13, 97658), null=True),
        ),
    ]
