# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_auto_20160720_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.AddField(
            model_name='order',
            name='uni_id',
            field=models.CharField(default='KNNF70JZ5TRCUNJI', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 11, 30, 10, 456169), null=True),
        ),
    ]
