# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_auto_20160720_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 11, 43, 37, 622053), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uni_id',
            field=models.CharField(default='EWZXHKBDFDDIDRPW', max_length=16, null=True),
        ),
    ]
