# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20160720_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 11, 46, 29, 381242), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uni_id',
            field=models.CharField(default='WHBMMSRLJVTHIQAV', max_length=16, null=True),
        ),
    ]
