# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160720_1032'),
        ('order', '0069_auto_20160720_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(default='ZIDO2A7ACLIMBJG3', max_length=16, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=128, null=True)),
                ('module_info', models.IntegerField(default=0, null=True)),
                ('delivered', models.IntegerField(default=0, null=True)),
                ('toBdelivered', models.IntegerField(default=0, null=True)),
                ('isMember', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 12, 6, 11, 660125), null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Price')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_info')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order_status')),
            ],
        ),
        migrations.CreateModel(
            name='Order_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('카드', '카드'), ('현금', '현금')], max_length=10, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
