# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_order_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 12, 7, 50, 343145), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uni_id',
            field=models.CharField(default='9JCF9EEQ28MWIB7I', max_length=16, null=True),
        ),
    ]
