# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_auto_20160720_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_info',
            name='numOfppl',
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 18, 20, 17, 91), null=True),
        ),
    ]
