# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_auto_20160721_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 21, 17, 1, 19, 469374), null=True),
        ),
    ]
