# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0087_auto_20160722_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 16, 50, 50, 330895), null=True),
        ),
        migrations.AlterField(
            model_name='shipping_info',
            name='iteration',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_iterate'),
        ),
    ]
