# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_auto_20160722_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 16, 52, 6, 963900), null=True),
        ),
        migrations.AlterField(
            model_name='shipping_info',
            name='duration',
            field=models.ForeignKey(default='1주', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping_duration'),
        ),
        migrations.AlterField(
            model_name='shipping_info',
            name='to_where',
            field=models.CharField(choices=[('0', '기본 배송지'), ('1', '주문자 정보와 동일'), ('2', '최근 배송지'), ('3', '새로운 배송\t')], default='기본 배송지', max_length=1, null=True),
        ),
    ]
