# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_auto_20160722_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 18, 35, 52, 143965), null=True),
        ),
    ]
