# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_auto_20160722_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end',
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
